### ISSUE TITLE
无样式

### ISSUE THREAD

**Issue by yamizero** [artchen/hexo-theme-typescript#10]
照着把依赖都安装了，hexo g ，hexo s 页面没有样式...报错：请问是什么原因呢...很喜欢你的简约风格的呢..
hexo d 之后 也无样式 报错是Typekit: the domain "yamizero.github.io" isn't in the list of published domains for kit "eyf3hir".

**Comment by artchen** [comment]
Typekit是字体服务。主题里hardcode了我的Typekit链接所以只会在我的域名加载。如果你不用Typekit可以直接去head里删掉。
没有样式的问题是style.css没有生成。请先参考 issue https://github.com/artchen/hexo-theme-typescript/issues/3 。

**Comment by artchen** [comment]
Duplicate to #3
