### ISSUE TITLE
部署后local search无法正常运行

### ISSUE THREAD

**Issue by logicislogic** [artchen/hexo-theme-typescript#11]
你好 很喜欢你的theme 我的问题是关于搜索的。
我在本地hexo s是可以正常运行local search的。但hexo d部署后就不灵了，大概是什么问题？

**Comment by artchen** [comment]
@jianfajun 你好。能提供一下具体的报错吗？

**Comment by bchart** [comment]
(我是提问者，换了一个账号)
更新一下问题：我同时部署在github和coding上，在github上搜索正常，编码也正常。但在coding上使用本地搜索，请求到的json文件解析是乱码，不是utf8编码。我把两个网页附在这里：
https://bchart.github.io
https://jianfajun.coding.me

**Comment by artchen** [comment]
@bchart 可能的原因是coding返回了content-type: x-gzip，应该可以通过在universal search里强制声明datatype来解决。

**Comment by artchen** [comment]
@bchart 请merge一下主分支最新的commit

**Comment by bchart** [comment]
@artchen 已解决 谢谢！
