### ISSUE TITLE
style.css 缺失，已经注释掉TY字体样式

### ISSUE THREAD

**Issue by SeonMe** [artchen/hexo-theme-typescript#12]
style .css缺失，已经试了#3但还是没解决。

**Comment by playmyswift** [comment]
请问解决了么

**Comment by playmyswift** [comment]
应该除了作者 没人能运行成功过....

**Comment by artchen** [comment]
统一回复在 issue https://github.com/artchen/hexo-theme-typescript/issues/3 。

**Comment by artchen** [comment]
Duplicate to #3
