### ISSUE TITLE
侧边栏 site-bio 代号

### ISSUE THREAD

**Issue by leewp14** [artchen/hexo-theme-typescript#13]
请问有侧边栏的代号吗？github源码好像没有demo网站的侧边栏设计 (site-bio)

**Comment by rikusen0335** [comment]
You mean "宅談" ?
It is the image so you can find it in `<theme name>/source/images/logo.png`.

**Comment by leewp14** [comment]
![screenshot_2018-07-18_23-46-26](https://user-images.githubusercontent.com/17796518/42892633-dbaaaba6-8ae4-11e8-9e02-826c3e64160f.png)
The element highlighted in blue. The element is labelled site-sidebar. 
This sidebar seems not available in the released theme source files. 
But I didn't use this theme anymore thus I think I will just close the issue. Thanks anyway @Rikusen0335
