### ISSUE TITLE
返回顶部的按钮

### ISSUE THREAD

**Issue by emuoiea** [artchen/hexo-theme-typescript#14]
sorry，没看到侧边弹出栏

**Comment by sumsun1987** [comment]
sorry，没看到侧边弹出栏``

**Comment by artchen** [comment]
Added sidebar support in latest commit.

**Comment by sumsun1987** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Art Chen"<notifications@github.com&gt;; 
发送时间: 2020年5月4日(星期一) 凌晨5:53
收件人: "artchen/hexo-theme-memory"<hexo-theme-memory@noreply.github.com&gt;; 
抄送: "____夏、末&amp;#x1F4AB;"<212549288@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [artchen/hexo-theme-memory] 返回顶部的按钮 (#14)





 
Closed #14.
