### ISSUE TITLE
请问改那个参数可以出现【查看全文】功能？

### ISSUE THREAD

**Issue by panyult** [artchen/hexo-theme-typescript#15]
就是在首页的时候，文章内容是展开的，我希望可以只显示文章的一部分，然后有个【查看全文】之类的按钮，点击跳转查看全文。谢谢

**Comment by artchen** [comment]
你可以自定义excerpt。
https://github.com/artchen/hexo-theme-typescript/blob/5a54acd21b003cf7952cc2c50e1277752adff04f/layout/_partial/post.ejs#L16
