### ISSUE TITLE
请问演示站不是用的 hexo 吗？

### ISSUE THREAD

**Issue by seekcx** [artchen/hexo-theme-typescript#17]
看了一下技术栈，用到了 react 和 gatsby。

非常喜欢这个主题，react 版本的主题有开源的打算吗？

**Comment by artchen** [comment]
是的，前不久玩了一把Gatsby但基本是custom build，我还没有研究过Gatsby Theme，所以开源还不好说。

**Comment by seekcx** [comment]
好的，谢谢！
