### ISSUE TITLE
内容显示不出来

### ISSUE THREAD

**Issue by zhuscat** [artchen/hexo-theme-typescript#4]
更换完主题后，博客首页内容显示不出来，只有导航栏，并且导航栏处于这样的状态：

<img width="611" alt="2016-11-20 10 39 57" src="https://cloud.githubusercontent.com/assets/14963619/20459927/fe763790-af0d-11e6-9b43-9bb4b98c12d7.png">

然后我输入了一些文章的路径查看，发现一些文章能显示出内容，一些文章不能显示出内容，不能显示出内容的文章导航栏也处于上面那张图片的状态。

然后我将不能显示出内容的文章的内容删除一部分就又能显示了，不知道是怎么回事。

不能显示的文章的出现的一些现象：

在控制台看可以看到内容已经有了，但就是没显示

<img width="579" alt="2016-11-20 10 40 21" src="https://cloud.githubusercontent.com/assets/14963619/20459949/f31de004-af0e-11e6-8072-f5e77e7f61c1.png">

<img width="440" alt="2016-11-20 10 40 35" src="https://cloud.githubusercontent.com/assets/14963619/20459950/f4559dcc-af0e-11e6-8b85-ff4c61e430e2.png">

**Comment by artchen** [comment]
是不是出问题的文章里有未闭合的html tag？

**Comment by artchen** [comment]
或者看看控制台里有没有js错误

**Comment by zhuscat** [comment]
js 到没有错误。点击查看网页源代码，发现以下情况：

正常显示的网页源代码：

![2016-11-21 10 02 48](https://cloud.githubusercontent.com/assets/14963619/20468452/e53836ec-afd1-11e6-8648-525d6241c1ca.png)

出现问题的：

![2016-11-21 10 02 30](https://cloud.githubusercontent.com/assets/14963619/20468455/eb183954-afd1-11e6-9460-6c5975adcf0d.png)

![2016-11-21 10 02 40](https://cloud.githubusercontent.com/assets/14963619/20468458/f0fe8a58-afd1-11e6-8f89-243a1c621b58.png)

![2016-11-21 10 02 54](https://cloud.githubusercontent.com/assets/14963619/20468460/f5023eec-afd1-11e6-8dda-c5c20c8faa65.png)

**Comment by artchen** [comment]
有可能是编码问题。保存文件的时候注意用utf-8试试看。

**Comment by zhuscat** [comment]
主要是我删掉文章的一部分内容那篇文章就能显示了，这应该不是编码问题吧。看了一下文章保存都是 UTF-8 的
2016年11月21日 13:00，Art Chen notifications@github.com写道：有可能是编码问题。保存文件的时候注意用utf-8试试看。

**Comment by artchen** [comment]
那可能问题在你删掉的部分上吧。这已经超过主题的范畴了。没有进一步的线索我也不知道该怎么帮你。

**Comment by artchen** [comment]
可以去检查一下/public里出问题的页面对应的生成文件。看看是不是generate的时候发生了乱码。

**Comment by zhuscat** [comment]
发现重新用 hexo 建了一遍博客问题就解决了。。。
