### ISSUE TITLE
右上角导航菜单木有样式

### ISSUE THREAD

**Issue by lepig** [artchen/hexo-theme-typescript#7]
<img width="302" alt="2016-12-15 22 57 29" src="https://cloud.githubusercontent.com/assets/5689279/21228925/a9cee7fc-c31a-11e6-9257-9603a44bcf6f.png">

那5个插件已经装了呀。在chrome里没有发现加载失败的资源文件。谢谢了

**Comment by artchen** [comment]
暂时没有在这个版本里做宅谈那种菜单。这就是该有的样式。

**Comment by lepig** [comment]
原来如此，谢谢
